server:
  port: 8085
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka
spring:
  application:
    name: comment-provider
  datasource:
    username: root
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/yst_vblog?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    password: 1234
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
  mapper-locations: classpath:com.yue.commentprovider.mapper/*.xml
logging:
  level:
    com.yue.commentprovider.mapper: debug